#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

// auxiliares
#define MAX_STRING 30

#define MAX_ANO 2050
#define MIN_ANO 2000

#define NAO_ENCONTRADO -1

// portateis
#define MAX_PORTATEIS 30

#define PORTATIL_DISPONIVEL 0
#define PORTATIL_REQUISITADO 1
#define PORTATIL_AVARIADO_TEMPORARIAMENTE 2
#define PORTATIL_AVARIADO_PERMANENTEMENTE 3

#define MAX_RAM 128
#define MIN_RAM 1

#define PROCESSADOR_I3 3
#define PROCESSADOR_I5 5
#define PROCESSADOR_I7 7

// requisicoes
#define MAX_DIAS_REQUISICAO 30
#define MAX_DIAS_PROLONGAR 7

#define MULTA 10

#define REQUISICAO_ATIVA 1
#define REQUISICAO_CONCLUIDA 0

#define TIPO_ESTUDANTE 1
#define TIPO_DOCENTE 2
#define TIPO_ADMIN 3

// avarias
#define AVARIA_REPARADA 0
#define AVARIA_TEMPORARIA 1
#define AVARIA_PERMANENTE 2

#endif // CONSTANTES_H_INCLUDED
